services:
  db:
    image: arm64v8/mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
    restart: unless-stopped
    
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: arm64v8/nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

  sftp:
    build:
      context: .
      dockerfile: sftp.Dockerfile
      args:
        SFTP_USER_DF: ${SFTP_USER}
        SFTP_PASSWORD_DF: ${SFTP_PASSWORD}
    user: "1000:1001"
    ports:
      - "${SFTP_PORT}"
    volumes:
      - ./app:/home/${SFTP_USER}/sftp
    restart: unless-stopped


volumes:
  data-db:
